version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - mynetwork

#nginx version: nginx/1.27.2
    nginx:
        image: nginx:1.27.2
        ports:
            - "8081:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        depends_on:
            - app
        networks:
            - mynetwork

    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: wordpress
            MYSQL_USER: kaixinjiuhao
            MYSQL_PASSWORD: cFzMv0Ha^&EIz&g6Va
            MYSQL_ROOT_PASSWORD: cFzMv0Ha^&EIz&g6Va
        ports:
            - "3307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
            - ./my.cnf:/etc/mysql/my.cnf
        networks:
            - mynetwork

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8001:80"
        environment:
            - PMA_HOST=47.106.115.51
        #      - PMA_HOST=wordpressadmin_mynetwork
        #      - PMA_USER=haitun
        #      - PMA_PASSWORD=cFzMv0Ha^&EIz&g6Va
        networks:
            - mynetwork
        depends_on:
            - mysql

networks:
    mynetwork:
        driver: bridge
volumes:
    dbdata:
